### ISSUE TITLE
Suggest support dividing half note into 3 equal length (2 = 2/3 + 2/3 + 2/3)

### ISSUE THREAD

**Issue by ZebraAlgebra** [yupingso/numbered-musical-notation#13]
Some worship songs uses the following group of notes: ![image](https://user-images.githubusercontent.com/113345510/211162571-345d7351-56f2-4bea-93ee-4f525d4e7c83.png)(e.g. 展開清晨的翅膀. 滿有能力 by 讚美之泉, or 上帝的兒女何等有福 in 367 of 世紀頌讚; perhaps some songs by 生命河靈糧堂 also does this)

Some current available workaround options:

1.  2/3+2/3+2/3 is very close to a Tresillo rhythm 3/4+3/4+1/2 ![image](https://user-images.githubusercontent.com/113345510/211162882-da274f50-3a0c-42a8-acc9-ce4a6cecf862.png). For songs with faster tempo, the difference is insignificant, but for slower songs the feel can be distinguishable.

2. A finer subdivision (1/3+1/3)+(1/3+1/3)+(1/3+1/3) along with ties can be used to accurately represent the same group of notes (using the current `_/3` suffix)), but this would cramp up the horizontal space, and the tie would interfere with the triplet notation as in the following: ![image](https://user-images.githubusercontent.com/113345510/211162999-e1ff4c4c-00d8-467a-bd76-4f27bb80c5bc.png)

**Comment by yupingso** [comment]
A `2/3+2/3+2/3` triplet is already supported with `4/3 4/3 3/3`. The syntax explanation is improved in commit 9dab7733d2749a5e1fbb19257046950c8bdb1d78.
